### ISSUE TITLE
server stops when  browser access localhost:8888 

### ISSUE THREAD

**Issue by fsmoreir** [muaz-khan/WebRTC-Scalable-Broadcast#1]
I start server.js and and a console message is printed: 
   info  - socket.io started
However when I access http://localhost:8888 in the browser an error occurs and the server stops.
with the following log:
C:\Users\Fernando\Dropbox\www\aaa\node_modules\webrtc-scalable-broadcast\server.js:12
    path.exists(filename, function (exists) {
         ^
TypeError: undefined is not a function
    at Server.<anonymous> (C:\Users\Fernando\Dropbox\www\aaa\node_modules\webrtc-scalable-broadcast\server.js:12:10)
    at Manager.handleRequest (C:\Users\Fernando\Dropbox\www\aaa\node_modules\webrtc-scalable-broadcast\node_modules\socket.io\lib\manager.js:588:28)
    at Server.<anonymous> (C:\Users\Fernando\Dropbox\www\aaa\node_modules\webrtc-scalable-broadcast\node_modules\socket.io\lib\manager.js:119:10)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

Maybe I am missing something?...

**Comment by fsmoreir** [comment]
This issue is resolved replacing "path.exists..." by "fs.existis..."  on line 12  (server.js)
